resources:
- repo: self
trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - '**/*.md'

variables:
- template: templates/vars.yml

jobs:
- job: macOS
  pool:
    vmImage: $(MACOS_VM_IMAGE)
  steps:
    - template: templates/setup-dotnet.yml
      parameters:
        version: $(DOTNET_SDK_VERSION)

    - task: Bash@3
      displayName: Build App
      inputs:
        targetType: 'inline'
        script: |
          dotnet build -c Debug -v Detailed
